server:
  port: 8081

spring:
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://34.207.28.209:3306/run?autoReconnect=true&userSSL=false&serverTimezone=UTC
    username: localhost
    password: 1q2w3e4r
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://34.207.28.209:3306/run?autoReconnect=true&userSSL=false&serverTimezone=UTC
    username: localhost
    password: 1q2w3e4r